version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'horoscope'
      MYSQL_USER: 'horoscope'
      MYSQL_PASSWORD: 'horoscope'
      MYSQL_ROOT_PASSWORD: 'hotoscope'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: 